### ISSUE TITLE
actions: some GitHub Actions jobs get stuck on 'records_test.py'

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#269]
Example: https://github.com/HEPData/hepdata/runs/1416821767

Some of the recent Travis CI jobs also failed on `records_test.py` and I had to restart them.  I added a test to `records_test.py` three weeks ago in commit 260bc75d8f51e71f22200fc805d9c8b257e2d417, but I'm not sure if it's related.

**Comment by alisonrclarke** [comment]
It looks like it's getting stuck before starting `records_test` so I'd guess it's not to do with your added test. Some suggestions:

 * Try adding `-vv` to the pytest call to see if that gives us any further debug info
 * Try renaming `records_test.py` so it runs in a different order, which might determine whether it's the start of `records_test.py` or the end of `old_inspire_ds_test.py` that's causing issues.

**Comment by alisonrclarke** [comment]
We've now got a [failure with a timeout](https://github.com/HEPData/hepdata/pull/273/checks?check_run_id=1447116834) which suggests the issue might be with getting a resource from hepdata.cedar.ac.uk in [`download_resource_file`](https://github.com/HEPData/hepdata/blob/0cb5bd62cf5eddca48e89511a53a88a978418e1d/hepdata/modules/records/utils/resources.py#L33).

@GraemeWatt is it worth adding a timeout in the `urlopen` call to avoid the hang? I guess this code should no longer be called on prod as we're no longer pulling in files from the old hepdata site, so it's just an issue with the tests using the old site. We'll get a test failure either way if the old site isn't responding.

**Comment by GraemeWatt** [comment]
The tests don't rely on [hepdata.cedar.ac.uk](http://hepdata.cedar.ac.uk) as far as I know.  The failure you pointed to is from [tests/records_test.py::test_update_record_info](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/tests/records_test.py#L408), which tests [update_record_info](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/hepdata/modules/records/utils/records_update_utils.py#L27).  This function calls [get_inspire_record_information](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/hepdata/modules/new_inspire_api/views.py#L41) which makes a request to the INSPIRE API using [resilient_requests](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/hepdata/resilient_requests.py#L37) implemented by Giuseppe.  As the name suggests, the request to the INSPIRE API is meant to be resilient, with a timeout and a retry strategy, so I'm not sure what's going wrong.

**Comment by GraemeWatt** [comment]
Ah, I see [ERROR:invenio-pidstore:Failed to register in DataCite](https://github.com/HEPData/hepdata/pull/273/checks?check_run_id=1447116834#step:13:348) in the failure you linked.  The [update_record_info](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/hepdata/modules/records/utils/records_update_utils.py#L90) function tries to push metadata to DataCite, but without authorisation credentials.  I've pushed a [commit](https://github.com/HEPData/hepdata/pull/273/commits/7dbdf2843903ea490e69ecd0b35d97d10c7d750c) to skip this step if `TESTING` and tests are now passing.  Alternatively, `NO_DOI_MINTING = True` could be set in the `config_local.gh.py` file.

**Comment by alisonrclarke** [comment]
I think in addition to the data cite errors there's still an issue in [line 254](https://github.com/HEPData/hepdata/pull/273/checks?check_run_id=1447116834#step:13:254) of the previous failure which points to [`download_resource_file`](https://github.com/HEPData/hepdata/blob/0cb5bd62cf5eddca48e89511a53a88a978418e1d/hepdata/modules/records/utils/resources.py#L33). 

Looking at the test submission used, [line 79](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/tests/test_data/test_submission/submission.yaml#L79) (and others) link to resources starting with `/resource`, which in [line 338 of submission.py](https://github.com/HEPData/hepdata/blob/bfd4ca7997e021ad0f23fe5946507e1b7905ea20/hepdata/modules/records/utils/submission.py#L338) are not treated as local resources but retrieved from the old hepdata site in `download_resource_file`.

Should I modify this and other test files so they're no longer reliant on the old hepdata, or at least reduce the number of times those types of resource files appear in the test submissions?

**Comment by GraemeWatt** [comment]
Good catch.  I didn't realise the tests were still dependent on the availability of [http://hepdata.cedar.ac.uk](http://hepdata.cedar.ac.uk).  This dependence should definitely be removed.  The corresponding [submission.yaml](https://github.com/HEPData/hepdata-submission/blob/master/examples/submission/TestHEPSubmission/submission.yaml) file in the `hepdata-submission` repo was updated to use local `.png` images.  The only issue is that the test coverage will be reduced if we don't test `download_resource_file`.  But eventually we'll anyway want to remove all parts of the code used for migration from [http://hepdata.cedar.ac.uk](http://hepdata.cedar.ac.uk).

**Comment by alisonrclarke** [comment]
So I guess the options are:

1. remove all but one `/resource` file from the submission, and add a timeout in `download_resource_file` to avoid hangs; or
2. remove all `/resources` and use `#pragma: no cover` to flag those lines as uncovered.

I think I'd prefer 1 for safety.

Do we have an issue to remove the migrator and all dependencies on hepdata.cedar.ac.uk?

**Comment by GraemeWatt** [comment]
Option 1 sounds good.  Just opened issue #276 to remove the old migrator code.
